name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Build and push gateway-flow-ui
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          platforms: linux/arm/v7
          tags: |
            ${{ env.REGISTRY }}/lorabridge2/gateway-flow-ui:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/lorabridge2/gateway-flow-ui:latest
          cache-to: type=inline
